server:
  port: 9090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
    queues:
      - recommendationQueue
      - anotherQueue

  application:
    name: match-inventory
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventoryDb
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service_url:
      defaultZone: http://localhost:8761/eureka