server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: match-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8090
          filters:
            - name: MyCustomFilter
          predicates:
            - Path=/api/user/**
        - id: purchase-service
          uri: http://localhost:8090
          filters:
            - name: MyCustomFilter
          predicates:
            - Path=/api/purchase/**
        - id: inventory-service
          uri: http://localhost:9090
          filters:
            - name: MyCustomFilter
          predicates:
            - Path=/api/product/**
        - id: recommendation-service
          uri: http://localhost:8085
          filters:
            - name: MyCustomFilter
          predicates:
            - Path=/api/recommend-product/**