server:
  port: 8085

spring:
  application:
    name: match-recommendation

eureka:
  instance:
    hostname: localhost
  client:
    service_url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        permittedCallsInHalfOpenState: 3
        minimumNumberOfCalls: 1
        waitDurationInOpenState: 10000ms
        failureRateThreshold: 50
